### ISSUE TITLE
error when trying to create presets

### ISSUE THREAD

**Issue by XelZero** [akogare62/decksetter#1]
when trying to do  !ds preset1 i get the following error:

[15:54:39.737] [command] ERROR: TypeError: Cannot read property 'includes' of undefined
    at C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox\mods\decksetter-master\index.js:124:30
    at Array.forEach (<anonymous>)
    at C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox\mods\decksetter-master\index.js:123:29
    at Array.forEach (<anonymous>)
    at checkPresetByRace (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox\mods\decksetter-master\index.js:121:18)
    at String.<anonymous> (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox\mods\decksetter-master\index.js:98:13)
    at CommandBase.exec (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox\mods\command\index.js:225:16)
    at hookCommand (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox\mods\command\index.js:81:29)
    at Dispatch.handle (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:414:45)

**Comment by akogare62** [comment]
Hi, use !ds 1 if still didn't works update ur opcode 
edit : my bad something wrong with last update, investigation in progress

**Comment by XelZero** [comment]
question i do have then is will this only choose card slot 1 on the list or can we actually set several so that itll do things when we enter each dgn - we have 10 to use so trying to make this easier on myself for not just the effects but also the presaves 1-10

**Comment by akogare62** [comment]
Fixed, if ur use "!ds 7 giant 9" this i ll set for ur actual location preset page 7, effect against giant and effect id 9 (goblin) 
And ll autoload ur saved setting when u enter in this location

**Comment by XelZero** [comment]
looks like that got it going - almost had another error but remaking the rule fixed it - thank you
