### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XelZero** [akogare62/decksetter#2]
[17:07:32.850] [mods] ERROR: Module "DeckSetter" (DeckSetter) could not be applied to server connection!
[17:07:32.852] [mods] ERROR: Please contact the module's author: https://discord.gg/659YbNY
[17:07:32.853] Error: [dispatch] [decksetter] hook: unmapped packet "S_CARD_DATA"
    at Dispatch.createHook (C:\Users\XXXXX\AppData\Local\Programs\TTB\node_modules\tera-network-proxy\lib\connection\dispatch.js:219:23)
    at Dispatch.hook (C:\Users\XXXXX\AppData\Local\Programs\TTB\node_modules\tera-network-proxy\lib\connection\dispatch.js:265:27)
    at Proxy.hook (C:\Users\ XXXXX\AppData\Local\Programs\TTB\bin\mod.js:280:36)
    at new CardSetter (C:\Users\ XXXXX\AppData\Local\Programs\TTB\mods\decksetter-master\index.js:110:7)
    at new <anonymous> (C:\Users\ XXXXX\AppData\Local\Programs\TTB\bin\mod-legacy-wrapper.js:144:13)
    at Mod.loadNetworkInstance (C:\Users\ XXXXX\AppData\Local\Programs\TTB\bin\mod.js:595:31)
    at ModManager.loadNetwork (C:\Users\ XXXXX\AppData\Local\Programs\TTB\bin\mod-manager.js:252:20)
    at C:\Users\ XXXXX\AppData\Local\Programs\TTB\bin\mod-manager.js:233:22
    at Map.forEach (<anonymous>)
    at ModManager.loadAllNetwork (C:\Users\ XXXXX\AppData\Local\Programs\TTB\bin\mod-manager.js:231:25)

**Comment by CatAnnaDev** [comment]
mod archived
